### ISSUE TITLE
微信联系人tableHeader悬停动画能做一下吗

### ISSUE THREAD

**Issue by juxiaohui** [TalkingJourney/SCIndexView#10]

**Comment by TalkingJourney** [comment]
我没理解你说的需求，请问你能具体描述下吗？

**Comment by juxiaohui** [comment]
看一下微信的联系人界面你就明白了，tableview header 有一个悬停的动画

**Comment by TalkingJourney** [comment]
section header悬停吗？

**Comment by juxiaohui** [comment]
是啊

**Comment by TalkingJourney** [comment]
section header悬停，不属于Index View，属于Table View。这个功能其实系统是默认提供的，把tableView的style设置成UITableViewStylePlain就可以了。

**Comment by juxiaohui** [comment]
好吧，你可能还是没明白我的意思，我说的是悬停的动画，如果你慢慢滑动微信通讯录界面，仔细观察当2个header悬停切换的时候，实际上是有一个渐变动画效果的，

**Comment by TalkingJourney** [comment]
@juxiaohui 你好，你之前开了这个issue，我认为此功能不应该是IndexView的功能，而是TableView的功能。但我在SCIndexViewDemo中，添加了实现此功能的方法，希望能给你一定的参考。详细代码请见以下commit：https://github.com/TalkingJourney/SCIndexView/commit/8734312543b03fa58ed0df52b01de8c90515b216
