### ISSUE TITLE
把sectionitem

### ISSUE THREAD

**Issue by huangping35** [TalkingJourney/SCIndexView#13]
-[SectionItem isEqualToString:]: unrecognized selector sent to instance 0x280eba040
warning: could not execute support code to read Objective-C class data in the process. This may reduce the quality of type information available.

**Comment by huangping35** [comment]
把sectionitem放到第一个就报错了

**Comment by huangping35** [comment]
[indexViewDataSource insertObject:sectionItem atIndex:0]; 这是因为什么？

**Comment by TalkingJourney** [comment]
[indexViewDataSource](https://github.com/TalkingJourney/SCIndexView/blob/6ed8d438d2128a401e8453f24301ec41a9257a80/SCIndexView/UITableView%2BSCIndexView.h#L31)的类型有限制，必须是NSString类型
