### ISSUE TITLE
- (NSUInteger)sectionOfTableViewDidScroll:(UITableView *)tableView 重写

### ISSUE THREAD

**Issue by curryfor30** [TalkingJourney/SCIndexView#15]
- (NSUInteger)sectionOfTableViewDidScroll:(UITableView *)tableView
如何重写，如何知道section 是多少。因为自己估算满足不了新需求，因为。A前面还有其他section，比如”我的企业“，但是”我的企业“section是不用出现在索引中的。

这样的话，不重写，原来默认的索引计算就满足不了了。老是超前一个。在A的时候就显示B，D的时候显示E

希望给点建议

**Comment by TalkingJourney** [comment]
- 目前不支持这个功能，当时写的时候，没有考虑到这种情况；
- (NSUInteger)sectionOfTableViewDidScroll:(UITableView *)tableView这个方法作用是：当滑动tableView时候，确定索引位置，而不是点击索引，确定tableview的section位置；
- 这个功能后续可以加上，但由于近期应该不会添加，如果你着急使用的话，可以fork或者下载源码，更改SCIndexView.m文件中的- (BOOL)continueTrackingWithTouch:(UITouch *)touch withEvent:(UIEvent *)event方法实现，来设置滑动索引时，设置你的currentSection。

**Comment by TalkingJourney** [comment]
[v2.2.0](https://github.com/TalkingJourney/SCIndexView/releases/tag/2.2.0) 已解决
