### ISSUE TITLE
悬停位置的sectionView背景色变色,怎么做,微信联系人的是变色的,求加上

### ISSUE THREAD

**Issue by SnailLoveSmile** [TalkingJourney/SCIndexView#24]

**Comment by TalkingJourney** [comment]
此功能不应该是IndexView的功能，应该是TableView的功能，所以我没有添加到SCIndexView的库中。
但在SCIndexViewDemo中，添加了实现此功能的方法。详细代码请见以下commit：https://github.com/TalkingJourney/SCIndexView/commit/8734312543b03fa58ed0df52b01de8c90515b216

**Comment by SnailLoveSmile** [comment]
谢谢
