### ISSUE TITLE
支持tableHeaderview和第一个索引位置

### ISSUE THREAD

**Issue by iOSleep** [TalkingJourney/SCIndexView#25]
如果有tableHeaderView的话，如果再最上面添加一个图片
类似微信最上面是个搜索框，索引第一个是一个🔍的图片
第一个数据源的话会导致数据里有+1这种代码来重新计算数据源并不是一个好的方式。。。

**Comment by TalkingJourney** [comment]
不好意思，我没有理解你的意思。【有🔍的图片的时候，第一个数据源的话会导致数据里有+1】
第一个数据源的话是什么意思？导致数据里有+1是什么意思？

**Comment by iOSleep** [comment]
我们希望保证数据源的纯洁，当你增加一个新的section用来显示搜索框的时候，你需要对一些section的计算做+-1操作

**Comment by TalkingJourney** [comment]
搜索框不作为UITableView的section，只是SCIndexView的第一个数据源
