### ISSUE TITLE
2.2.1版本索引偏移错误

### ISSUE THREAD

**Issue by forkdog** [TalkingJourney/SCIndexView#29]
![](http://ww1.sinaimg.cn/large/006tNc79gy1g4gx9q3r9fg308i0hiq3g.gif)

**Comment by TalkingJourney** [comment]
你能详细描述复现这个问题的方法，或者提供使用库的代码或者demo也可以

**Comment by cocoZ** [comment]
我这里也有同样的问题，

**Comment by cocoZ** [comment]
CGFloat offsetMaxY = self.tableView.contentSize.height + self.tableView.contentInset.bottom - self.tableView.bounds.size.height;

这行代码， 当contentSize.height  小于bounds.size.height 时，   offsetMaxY 会有负数的情况

**Comment by TalkingJourney** [comment]
感谢你的提醒，我最近有些忙，如果可以，你可以修复问题，并提一个PR，感谢

**Comment by TalkingJourney** [comment]
@forkdog  @cocoZ  我近期修复下吧
