### ISSUE TITLE
只有两种字母索引的时候点击索引位置错乱

### ISSUE THREAD

**Issue by SunSevi** [TalkingJourney/SCIndexView#31]
<img width="300" alt="image" src="https://user-images.githubusercontent.com/19682231/61107612-ebe07300-a4b2-11e9-8a45-c543e0a29214.png">

**Comment by panwang** [comment]
SCindexView.m 230行，当数据量小的时候计算出来的offSetMaxY是负值，offsetMaxY = offsetMaxY>0?offsetMaxY:0;加上这句
