### ISSUE TITLE
iPhone X显示问题

### ISSUE THREAD

**Issue by LwcXing** [TalkingJourney/SCIndexView#34]
iPhone X上不会默认选中第一个，但是demo运行没有问题，对比demo和我写的代码，没发现有啥特别之处导致会出现这样的问题
![IMG_76CDD0A95E5B-1](https://user-images.githubusercontent.com/26810686/64949456-ce14fd00-d8ab-11e9-8b6e-77195e8dae7d.jpeg)

**Comment by LwcXing** [comment]
已解决

**Comment by huxq-coder** [comment]
可以请问下怎么解决的吗，我也遇到了这个问题，非常感谢 @LwcXing
