### ISSUE TITLE
TableViewStyle问题

### ISSUE THREAD

**Issue by shwrt2016** [TalkingJourney/SCIndexView#36]
当tableviewStyle为group类型的时候，第一个索引随滑动会闪烁，plain没问题

**Comment by TalkingJourney** [comment]
我这边用2.2.2，iOS13.1.3，没有这个问题。
你使用的库是哪个版本，手机系统是哪个版本？

**Comment by shwrt2016** [comment]
> 我这边用2.2.2，iOS13.1.3，没有这个问题。
> 你使用的库是哪个版本，手机系统是哪个版本？

手机系统12.4.1，库是2.2.2最新的
