### ISSUE TITLE
没有相应的属性调整索引元素的字体大小嘛？

### ISSUE THREAD

**Issue by nongmogege** [TalkingJourney/SCIndexView#37]
如题

**Comment by TalkingJourney** [comment]
不能单独设置，设置indexItemHeight这个属性，字体大小也会跟着改变的

**Comment by nongmogege** [comment]
> 不能单独设置，设置indexItemHeight这个属性，字体大小也会跟着改变的

嗯，这样的话，就不能进行特殊字体，比如粗体的设置了，希望可以进行改进

**Comment by TalkingJourney** [comment]
https://github.com/TalkingJourney/SCIndexView/commit/7b38373078881845b64b174bb629e385ff606631 已解决
