### ISSUE TITLE
选择C，索引自动变成了B， 很大概率选择一个之后又自动变成上一个

### ISSUE THREAD

**Issue by WadonLiu** [TalkingJourney/SCIndexView#44]
解决方法
configCurrentSection
172行
if (sectionFrame.origin.y + sectionFrame.size.height - self.tableView.contentOffset.y > insetTop+1) {

**Comment by kkkelicheng** [comment]
都2022年了，这个bug还没解决。。。
按照你的方案加了。ok

**Comment by kkkelicheng** [comment]
貌似这个问题跟
```
#define kSCIndexViewInsetTop (self.translucentForTableViewInNavigationBar ? UIApplication.sharedApplication.statusBarFrame.size.height + 44 : 0)
```
有关。
所以，可以把translucentForTableViewInNavigationBar设置为false。。。

**Comment by songbai1211** [comment]
> 都2022年了，这个bug还没解决。。。 按照你的方案加了。ok

我加了这个貌似还是无法选中最后一，老哥你解决了吗？你说的那个false 我也设置了也没用
