### ISSUE TITLE
数据少时最下面几个索引无法点击选中状态

### ISSUE THREAD

**Issue by fanzK12** [TalkingJourney/SCIndexView#46]
当所有数据不足当前页面展示时，无法选中最后面几个索引，可否支持也能选中状态，类似微信如果数据到最底部时，最后几个索引也可以点击选中状态。（数据足够多的时候，但最后几个分区数据不足一屏时，划到最低部时，最后几个索引也是无法选中状态）

**Comment by fanzK12** [comment]
可否无论数据多还是少，任何情况都可以支持索引选中状态

**Comment by TalkingJourney** [comment]
最后几个section，数据不足一屏时，微信也是无法实现选中状态的

**Comment by TalkingJourney** [comment]
https://github.com/TalkingJourney/SCIndexView/issues/42

**Comment by fanzK12** [comment]
大神，我的意思是支持点击索引选中状态，滑动时依旧不变，点击任意索引都可以变为选中状态

**Comment by TalkingJourney** [comment]
1、“点击索引选中状态”是指点击索引的时候，自动将tableView展示该索引对应的section位置，该索引为选中状态。如果是这个意思的话，目前是支持这个功能的。
2、“滑动时依旧不变”是指滑动到底部时，对应索引没有变为选中状态。如果是这个意思的话，是因为你没有滑动对应的section到tableView的top位置。
3、“点击任意索引都可以变为选中状态”，同第1条，只是当后面的section数据少时，不足一屏，会自动跳到tableview的top对应的section。
如果你的设备不是这样的话，说明和系统或者设备有关系，可以提供给我，我尝试下，也可以给我录个视频，发到我邮箱。

**Comment by fanzK12** [comment]
大神，“点击索引选中状态”：点击索引的时候，自动将tableView展示该索引对应的section位置，这个没问题，但是后面的section数据少时，不足一屏，tableview会自动跳到tableview的top对应的section，这个时候右侧的索引希望也可以是点击的那个选中状态。因为我们项目中有这样的数据，一个tableview的section可能只有一个或者两三个，每个section的数据也只有1个或者几个，根本不足一屏，点击右侧的索引列表也不会有什么变化，但是希望点击索引的时候都能有选中状态，尽管列表没有变化。辛苦大神

**Comment by fanzK12** [comment]
大神，“点击索引选中状态”：点击索引的时候，自动将tableView展示该索引对应的section位置，这个没问题，但是后面的section数据少时，不足一屏，tableview会自动跳到tableview的top对应的section，这个时候右侧的索引希望也可以是点击的那个选中状态。因为我们项目中有这样的数据，一个tableview的section可能只有一个或者两三个，每个section的数据也只有1个或者几个，根本不足一屏，点击右侧的索引列表也不会有什么变化，但是希望点击索引的时候都能有选中状态，尽管列表没有变化。这样能让用户知道点的是哪个！辛苦大神

**Comment by TalkingJourney** [comment]
“点击右侧的索引列表也不会有什么变化，但是希望点击索引的时候都能有选中状态，尽管列表没有变化。这样能让用户知道点的是哪个”：点击右侧会有索引提示的，用户是可以看到索引提示的

**Comment by fanzK12** [comment]
这个是有的，可否添加个功能，支持这种情况下的选中状态，加个开关配置也可以，谢谢大神

**Comment by TalkingJourney** [comment]
我觉得这个需求是不合理。因为在最后几个 section 数据比较少的时候，滑动 tableView，最后几个索引是不会被选到的，但是点击右边索引是可以选到，这里逻辑就不一致了

**Comment by fanzK12** [comment]
好的，我去说服产品经理去😂，谢谢大神

**Comment by TalkingJourney** [comment]
没关系

**Comment by songbai1211** [comment]
能支持选中吗？现在默认进去选中了最后一个，然后点击上面的，有跳回到最后一个，这个像个bug，微信是没有选中的状态，看着正常，
