### ISSUE TITLE
崩溃

### ISSUE THREAD

**Issue by SmallTwoInn** [TalkingJourney/SCIndexView#5]
## 运行SCIndexViewDemo项目 ， 选择“指向型类型- V2.x”和“中心提示弹层-V2.x”  push到相应的控制器， 然后返回回到“选择索引类型”的主界面， 出现崩溃 还望及时更新  

真机调试   6sPlus  系统 10.3.2

崩溃信息
**'NSInternalInconsistencyException', reason: 'An instance 0x10107dc00 of class UITableView was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x174223160>**

**Comment by SmallTwoInn** [comment]
V2.x的崩溃  1.x的不崩溃

**Comment by TalkingJourney** [comment]
v2.0.2 已修复
