### ISSUE TITLE
[UITableView(SCIndexView) SCIndexView_layoutSubviews] (UITableView+SCIndexView.m:)

### ISSUE THREAD

**Issue by MarilynRose** [TalkingJourney/SCIndexView#51]
UIKitCore | -[UITableView _updateFocusAfterLoadingCellsWithFocusedView:viewType:] + 200
-- | --
11 UIKitCore | -[UITableView _endUpdatingVisibleCells:originalContentOffset:focusedView:focusedViewType:] + 172
12 UIKitCore | -[UITableView _updateVisibleCellsNow:] + 3460
13 UIKitCore | -[UITableView layoutSubviews] + 356
14 DUApp | -[UITableView(SCIndexView) SCIndexView_layoutSubviews] (UITableView+SCIndexView.m:50)
15 UIKitCore | -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 2500

**Comment by TalkingJourney** [comment]
遇到什么问题？完整叙述下
