### ISSUE TITLE
当通过present时,右侧索引视图滑动失效.

### ISSUE THREAD

**Issue by YueHooo** [TalkingJourney/SCIndexView#52]
当通过presentviewcontroller到tableview页面后(系统大于ios 13),右侧的索引视图滑动时会失效,只能通过点击进行与tableview的互动,而无法通过正常滑动进行.
尝试将scindexview的demo中push改为present后该问题也在示例demo中出现.是否有较好的解决办法?感谢回复!

**Comment by TalkingJourney** [comment]
你需要设置 viewController.modalPresentationStyle = UIModalPresentationFullScreen，present 半屏，系统有滑动手势

**Comment by ChaoYeee** [comment]
想保持present半屏效果,右侧索引视图手势冲突是否有好的解决办法?

**Comment by YueHooo** [comment]
> 你需要设置 viewController.modalPresentationStyle = UIModalPresentationFullScreen，present 半屏，系统有滑动手势

想保持present半屏效果,右侧索引视图手势冲突是否有好的解决办法?
