### ISSUE TITLE
索引比较少的时候，最后几个无法选中，这个有解决方法吗？因为有选中态，每次点一下下面的字母，都跳回到之前的选中？

### ISSUE THREAD

**Issue by songbai1211** [TalkingJourney/SCIndexView#53]
索引比较少的时候，最后几个无法选中，这个有解决方法吗？因为有选中态，每次点一下下面的字母，都跳回到之前的选中？这个能加个方法吗？要不然看着很奇怪。。

**Comment by TalkingJourney** [comment]
https://github.com/TalkingJourney/SCIndexView/issues/42
