### ISSUE TITLE
求解决 关于索引数据源中包含UITableViewIndexSearch对象时候

### ISSUE THREAD

**Issue by yj9294** [TalkingJourney/SCIndexView#7]
需求是这样的我的第一个索引应为一个🔍，但是UITableViewIndexSearch会转成“{search}”串，而不能类似系统自带的转换为一个放大镜图标。求解决 目前这个索引必须要使用搜索功能。

**Comment by muwan** [comment]
同求，tableview有一个常量UITableViewIndexSearch，是在索引显示放大镜的

**Comment by TalkingJourney** [comment]
@yj9294 @muwan v2.1.0已解决
