### ISSUE TITLE
关于SCIndexView创建后，tableView位置变化的问题

### ISSUE THREAD

**Issue by darkhandz** [TalkingJourney/SCIndexView#8]
假设有如下代码在viewDidLoad里执行，1秒后，SCIndexView的位置就有点尴尬了，有没有提供什么方法调整呢？（我目前只能用注释里的那种方法来达到执行SCIndexView的initWithTableview从而让它重新获取tableView.frame的效果）

![snipaste_2018-03-07_14-18-27](https://user-images.githubusercontent.com/2143333/37076655-8db4a84c-2212-11e8-9ea9-3bbc50ae7a3c.png)

tableView位置变化后：

![image](https://user-images.githubusercontent.com/2143333/37076788-063c66b0-2213-11e8-80eb-6cdbec7152ae.png)

**Comment by TalkingJourney** [comment]
@darkhandz 我内部只是kvo监听UITableView的frame，当tableview的frame发生变化时，indexview会跟随变化，如果你通过autolayout进行布局的话，改变约束时，kvo的回调不会执行，你可以通过frame方式设置布局，后续我进行优化

**Comment by darkhandz** [comment]
好的，感谢👏
